[build]
  publish = "build"
  command = "npm run build"
  ignore = "/api/"

[build.environment]
  NODE_VERSION = "18"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
