[build]
  base = "."
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
